import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from "next/head";
import { Poppins } from "@next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from 'react-bootstrap/Navbar';
import 'bootstrap/dist/css/bootstrap.min.css';
import {
    RecoilRoot
} from 'recoil';
import { Container, Nav } from 'react-bootstrap';

const poppins = Poppins({
    weight: '300',
    subsets: ['latin']
})

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <RecoilRoot>
                <Head>
                    <title>AdmonDB</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />

                    
                </Head>
                <div className={`${poppins.className} flex flex-col items-center justify-center bg-gray-200 h-screen w-screen `}>
               
                    <Component {...pageProps} />
                    <Toaster />
                </div>
            </RecoilRoot>

        </>
    )
}
